apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-smtp-secret
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: homelab/infra/kv-secret
  path: shared/notifications
  rolloutRestartTargets:
    - kind: Deployment
      name: kube-prometheus-stack-grafana
  destination:
    name: grafana-smtp-secret
    create: true
    transformation:
      excludeRaw: true
      excludes:
        - ".*" 
      templates:
        smtp_endpoint:
          text: '{{ .Secrets.smtp_endpoint }}'
        smtp_username:
          text: '{{ .Secrets.smtp_username }}'
        smtp_password:
          text: '{{ .Secrets.smtp_password }}'
        smtp_from_address:
          text: '{{ .Secrets.smtp_from_address }}'
        smtp_receiver:
          text: '{{ .Secrets.smtp_receiver }}'