apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache
  namespace: renovate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 5Gi