apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: renovate-github-token
  namespace: renovate
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: homelab/infra/kv-secret
  path: shared/github-token
  destination:
    create: true
    name: renovate-github-token
    transformation:
      excludeRaw: true