namespaceOverride: monitoring

# Note: User and group 65534 were chosen to be able to read Kubernetes audit log file

alloy:
  configMap:
    create: false
    name: alloy-config
    key: config.hcl
  listenAddr: 0.0.0.0
  storagePath: /var/mnt/homelab/alloy-wal
  mounts:
    # Mount /var/log from the **host** into the container for log collection
    varlog: false
    # Mount /var/lib/docker/containers from the host into the container for log collection
    dockercontainers: false
    extra:
      - name: alloy-wal
        mountPath: /var/mnt/homelab/alloy-wal
        readOnly: false
      - name: kubernetes-audit-logs
        mountPath: /var/log/audit/kube/kube-apiserver.log
        readOnly: true
  enableReporting: false
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

controller:
  type: daemonset
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  volumes:
    extra:
      - name: alloy-wal
        hostPath:
          path: /var/mnt/homelab/alloy-wal
          type: DirectoryOrCreate
      - name: kubernetes-audit-logs
        hostPath:
          path: /var/log/audit/kube/kube-apiserver.log
  initContainers:
    - name: wal-setup
      image: busybox
      command: ["sh", "-c", "chown -R 65534:65534 /var/mnt/homelab/alloy-wal"]
      volumeMounts:
        - name: alloy-wal
          mountPath: /var/mnt/homelab/alloy-wal
      securityContext:
        runAsUser: 0

configReloader:
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true