apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: karakeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.11.1
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch
          envFrom:
            - secretRef:
                name: karakeep-secrets
            - configMapRef:
                name: karakeep-configuration
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: meilisearch
          persistentVolumeClaim:
            claimName: meilisearch-pvc