apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultwarden-oauth-secret
  namespace: vaultwarden
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: homelab/infra/kv-secret
  path: platforms/oauth/vaultwarden
  rolloutRestartTargets:
    - kind: StatefulSet
      name: vaultwarden
  destination:
    name: vaultwarden-oauth-secret
    create: true
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
        SSO_CLIENT_ID:
          text: '{{ .Secrets.client_id }}'
        SSO_CLIENT_SECRET:
          text: '{{ .Secrets.client_secret }}'
        SSO_AUTHORITY:
          text: '{{ .Secrets.discovery_endpoint }}'