apiVersion: v1
kind: ConfigMap
metadata:
  name: changedetection-config
  namespace: changedetection
data:
  PORT: "5000"
  TZ: "Africa/Cairo"
  LOGGER_LEVEL: "WARNING"
  BASE_URL: "changedetection.homelab.ikabbash.com"