apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: n8n-postgres-credentials
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: homelab/apps/kv-secret
  path: n8n
  rolloutRestartTargets:
    - kind: Deployment
      name: n8n
  destination:
    create: true
    name: n8n-postgres-credentials
    transformation:
      excludeRaw: true
      excludes:
        - ".*" 
      templates:
        # n8n
        DB_POSTGRESDB_HOST:
          text: 'postgres'
        DB_POSTGRESDB_PORT:
          text: '5432'
        DB_POSTGRESDB_DATABASE:
          text: '{{ .Secrets.db_name }}'
        DB_POSTGRESDB_USER:
          text: '{{ .Secrets.db_user }}'
        DB_POSTGRESDB_PASSWORD:
          text: '{{ .Secrets.db_password }}'
        # PostgreSQL
        POSTGRES_DB:
          text: '{{ .Secrets.db_name }}'
        POSTGRES_USER:
          text: '{{ .Secrets.db_user }}'
        POSTGRES_PASSWORD:
          text: '{{ .Secrets.db_password }}'