apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: n8n-storage
  name: n8n-storage
  namespace: n8n
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi