apiVersion: v1
kind: ConfigMap
metadata:
  name: karakeep-configuration
  namespace: karakeep
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  DATA_DIR: "/data"
  NEXTAUTH_URL: "https://karakeep.homelab.ikabbash.com"
  BROWSER_WEB_URL: "http://chrome:9222"
  MEILI_ADDR: "http://meilisearch:7700"
  WORKERS_HOST: "0.0.0.0"
  WORKERS_PORT: "8080"
  LOG_LEVEL: "warning"
  DB_WAL_MODE: "true"
  DISABLE_SIGNUPS: "true"
  DISABLE_PASSWORD_AUTH: "true"