apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: karakeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep-web
  template:
    metadata:
      labels:
        app: karakeep-web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: fix-run-perms
          image: busybox
          command: ["sh", "-c", "mkdir -p /run && chown 1000:1000 /run"]
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
          volumeMounts:
            - mountPath: /run
              name: run
      containers:
        - name: web
          image: ghcr.io/karakeep-app/karakeep:0.31.0
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /run
              name: run
            - mountPath: /tmp
              name: tmp
          envFrom:
            - secretRef:
                name: karakeep-secrets
            - secretRef:
                name: karakeep-smtp-secret
            - secretRef:
                name: karakeep-llm-secret
            - secretRef:
                name: karakeep-oauth-secret
            - configMapRef:
                name: karakeep-configuration
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}