apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: miniflux-oauth
  namespace: miniflux
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: homelab/infra/kv-secret
  path: platforms/oauth/miniflux
  rolloutRestartTargets:
    - kind: Deployment
      name: miniflux
  destination:
    create: true
    name: miniflux-oauth
    transformation:
      templates:
        OAUTH2_PROVIDER:
          text: 'oidc'
        OAUTH2_CLIENT_ID:
          text: '{{ .Secrets.client_id }}'
        OAUTH2_CLIENT_SECRET:
          text: '{{ .Secrets.client_secret }}'
        OAUTH2_REDIRECT_URL:
          text: '{{ .Secrets.redirect_url }}'
        OAUTH2_OIDC_DISCOVERY_ENDPOINT:
          text: '{{ .Secrets.discovery_endpoint }}'
        OAUTH2_USER_CREATION:
          text: '1'