apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ikabbash/homelab.git
    targetRevision: HEAD
    path: manifests/nginx2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true