apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: postgres-network-policy
  namespace: miniflux
spec:
  endpointSelector:
    matchLabels:
      app: postgres
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: miniflux
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
  egress:
    - {}