apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: miniflux-postgres-credentials
  namespace: miniflux
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  vaultAuthRef: default
  type: kv-v2
  mount: homelab/apps/kv-secret
  path: miniflux
  rolloutRestartTargets:
    - kind: Deployment
      name: miniflux
  destination:
    create: true
    name: miniflux-postgres-credentials
    transformation:
      templates:
        POSTGRES_USER:
          text: '{{ .Secrets.db_user }}'
        POSTGRES_PASSWORD:
          text: '{{ .Secrets.db_password }}'
        POSTGRES_DB:
          text: '{{ .Secrets.db_name }}'
        DATABASE_URL:
          text: 'postgres://{{ .Secrets.db_user }}:{{ .Secrets.db_password }}@postgres/{{ .Secrets.db_name }}?sslmode=disable'